server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: lwpPeter1023
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #  main:
#    allow-circular-references: true
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml


